### ISSUE TITLE
Pagination is not centered

### ISSUE THREAD

**Issue by SystemZ** [lvlup-pro/spawn-frontend-material#35]
Old trick:

```css
.pagination {
        justify-content: center;
    }
```

Doesn't work anymore on vuetify 0.8.8
